apiVersion: v1
kind: Service
metadata:
  name: medicure-service
  labels:
    app: medicure
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: medicure