---
- name: Configure Kubernetes Cluster
  hosts: local
  tasks:
    - name: Ensure kubectl is configured
      command: kubectl cluster-info
      register: cluster_info
      changed_when: false

    - name: Create namespaces
      command: kubectl apply -f kubernetes/namespace.yaml
      args:
        chdir: /var/lib/jenkins/workspace/medicure-pipeline

    - name: Display cluster information
      debug:
        msg: "{{ cluster_info.stdout_lines }}"