---
- name: Deploy Medicure Application
  hosts: local
  vars:
    namespace: "{{ lookup('env', 'NAMESPACE') | default('medicure-test', true) }}"
  tasks:
    - name: Deploy application to Kubernetes
      command: kubectl apply -f kubernetes/deployment.yaml -n {{ namespace }}
      args:
        chdir: /var/lib/jenkins/workspace/medicure-pipeline

    - name: Deploy service
      command: kubectl apply -f kubernetes/service.yaml -n {{ namespace }}
      args:
        chdir: /var/lib/jenkins/workspace/medicure-pipeline

    - name: Wait for deployment
      command: kubectl rollout status deployment/medicure-app -n {{ namespace }} --timeout=300s

    - name: Get service details
      command: kubectl get svc medicure-service -n {{ namespace }}
      register: svc_output

    - name: Display service
      debug:
        msg: "{{ svc_output.stdout_lines }}"